package main

import (
	"bufio"
	"context"
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/pion/ice/v4"
	"github.com/pion/stun/v4"
)

type SessionInfo struct {
	Ufrag      string   `json:"ufrag"`
	Pwd        string   `json:"pwd"`
	Candidates []string `json:"candidates"`
}

type Session struct {
	agent *ice.Agent
	conn  *ice.Conn
}

var CurrentSession *Session

func main() {
	role := flag.String("role", "", "Role to run: 'listener' or 'host'")
	flag.Parse()

	if *role != "listener" && *role != "host" {
		fmt.Println("Usage:")
		fmt.Println("  go run . -role listener   (Start the listener in Terminal 1)")
		fmt.Println("  go run . -role host       (Start the host in Terminal 2)")
		os.Exit(1)
	}

	isHost := *role == "host"
	fmt.Printf("\n=== RUNNING AS %s ===\n", strings.ToUpper(*role))

	// 1. Multiple STUN servers on BOTH standard port 3478 and Google's 19302
	stunServers := []string{
		"stun:stun.cloudflare.com:3478",
		"stun:stun.l.google.com:19302",
		"stun:stun1.l.google.com:19302",
	}

	var stunURIs []*stun.URI
	for _, rawURI := range stunServers {
		u, err := stun.ParseURI(rawURI)
		if err == nil {
			stunURIs = append(stunURIs, u)
		}
	}

	// 2. Initialize Agent with IP filter
	agent, err := ice.NewAgentWithOptions(
		ice.WithUrls(stunURIs),
		ice.WithNetworkTypes([]ice.NetworkType{ice.NetworkTypeUDP4}),
		ice.WithIncludeLoopback(),
		ice.WithIPFilter(func(ip net.IP) bool {
			// Ignore virtual container subnets (Docker 172.16-31.x.x and libvirt 192.168.122.x)
			if ipf := ip.To4(); ipf != nil {
				isDocker := ipf[0] == 172 && (ipf[1] >= 16 && ipf[1] <= 31)
				isVirbr0 := ipf[0] == 192 && ipf[1] == 168 && ipf[2] == 122
				if isDocker || isVirbr0 {
					return false
				}
			}
			return true
		}),
	)
	if err != nil {
		panic(err)
	}

	CurrentSession.agent = agent

	defer agent.Close()

	// 3. Monitor connection state
	_ = agent.OnConnectionStateChange(func(s ice.ConnectionState) {
		fmt.Printf("🔄 [State]: %s\n", s)
	})

	// 4. Gather candidates
	var candidates []string
	var mu sync.Mutex
	gatherDone := make(chan struct{})

	_ = agent.OnCandidate(func(c ice.Candidate) {
		fmt.Println("candidate", c)
		if c == nil {
			close(gatherDone)
			return
		}
		mu.Lock()
		candidates = append(candidates, c.Marshal())
		mu.Unlock()
	})

	fmt.Println("🔍 Gathering candidates (local network + public internet STUN)...")
	_ = agent.GatherCandidates()
	<-gatherDone
	fmt.Println("✅ Candidate gathering complete.")

	// Validate whether this computer discovered its public IP
	hasPublic := false
	for _, c := range candidates {
		fmt.Println("candidat epublic ip check", c)
		if strings.Contains(c, "typ srflx") {
			hasPublic = true
			break
		}
	}

	if hasPublic {
		fmt.Println("🌐 Public internet IP (STUN) discovered successfully!")
	} else {
		fmt.Println("⚠️  WARNING: Could NOT discover your public internet IP!")
		fmt.Println("   STUN UDP requests were blocked by your router, firewall, or VPN.")
		fmt.Println("   Connecting across the internet will fail unless you are on the same Wi-Fi.")
	}

	ufrag, pwd, err := agent.GetLocalUserCredentials()
	if err != nil {
		panic(err)
	}

	localSession := SessionInfo{
		Ufrag:      ufrag,
		Pwd:        pwd,
		Candidates: candidates,
	}

	localEncoded, _ := encodeSession(localSession)
	reader := bufio.NewReader(os.Stdin)
	var remoteSession SessionInfo

	if !isHost {
		// LISTENER FLOW
		fmt.Println("\n-----------------------------------------------------------")
		fmt.Println("Step 1: Copy this string and paste it into the HOST:")
		fmt.Println(localEncoded)
		fmt.Println("-----------------------------------------------------------")

		fmt.Print("\nStep 2: Paste the string generated by the HOST here:\n> ")
		remoteStr, _ := reader.ReadString('\n')
		remoteSession, err = decodeSession(strings.TrimSpace(remoteStr))
		if err != nil {
			fmt.Printf("Failed to decode host string: %v\n", err)
			return
		}
	} else {
		// HOST FLOW
		fmt.Print("\nStep 1: Paste the string generated by the LISTENER here:\n> ")
		remoteStr, _ := reader.ReadString('\n')
		remoteSession, err = decodeSession(strings.TrimSpace(remoteStr))
		if err != nil {
			fmt.Printf("Failed to decode listener string: %v\n", err)
			return
		}

		fmt.Println("\n-----------------------------------------------------------")
		fmt.Println("Step 2: Copy this string and paste it back into the LISTENER:")
		fmt.Println(localEncoded)
		fmt.Println("-----------------------------------------------------------")
	}

	// 5. Add remote candidates and verify if the remote peer has a public IP
	remoteHasPublic := false
	for _, candStr := range remoteSession.Candidates {
		if strings.Contains(candStr, "typ srflx") {
			remoteHasPublic = true
		}
		c, err := ice.UnmarshalCandidate(candStr)
		if err != nil {
			continue
		}
		_ = agent.AddRemoteCandidate(c)
	}

	if !remoteHasPublic {
		fmt.Println("\n❌ ERROR: The other peer has NO public STUN candidate!")
		fmt.Println("   The other machine only gathered private Wi-Fi IPs (192.168.x.x).")
		fmt.Println("   Their router, firewall, or VPN is blocking STUN.")
		fmt.Println("   (Connection cannot traverse the public internet without a public IP).")
	}

	// Give internet checks 30 seconds to punch through
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	var conn *ice.Conn
	fmt.Println("\n⚡ Performing ICE Handshake across the internet...")

	if isHost {
		conn, err = agent.Dial(ctx, remoteSession.Ufrag, remoteSession.Pwd)
	} else {
		conn, err = agent.Accept(ctx, remoteSession.Ufrag, remoteSession.Pwd)
	}

	CurrentSession = &Session{
		agent: agent,
		conn:  conn,
	}

	if err != nil {
		fmt.Printf("\n❌ Connection Failed: %v\n", err)
		if !remoteHasPublic || !hasPublic {
			fmt.Println("👉 Cause: Missing public STUN candidate on one or both peers.")
		}
		return
	}
	defer conn.Close()

	fmt.Println("\n🎉 CONNECTION ESTABLISHED ACROSS THE INTERNET!")
	selectedPair, err := agent.GetSelectedCandidatePair()
	if err == nil && selectedPair != nil {
		fmt.Printf("🏆 Selected Path: %s <---> %s\n", selectedPair.Local.Address(), selectedPair.Remote.Address())
	}
	fmt.Println("==================================================")

	// Run receiver concurrently in the background for both host and listener
	go CurrentSession.RecieveAudio()

	if isHost {
		CurrentSession.SendAudio()
	}

	// Keep connection alive to continue listening
	select {}
}

func encodeSession(s SessionInfo) (string, error) {
	b, err := json.Marshal(s)
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(b), nil
}

func decodeSession(s string) (SessionInfo, error) {
	var info SessionInfo
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		return info, err
	}
	err = json.Unmarshal(b, &info)
	return info, err
}

func (s *Session) SendAudio() {
	filePath := "/home/yuri/Data/projects/Go-p2p/p2p-mpv/excluded/tst.m4a"
	file, err := os.Open(filePath)
	if err != nil {
		fmt.Printf("❌ Failed to open audio file: %v\n", err)
		return
	}
	defer file.Close()

	tee := io.TeeReader(file, s.conn)

	buf := make([]byte, 1200)
	totalBytes := 0

	fmt.Printf("🚀 [Sender]: Streaming %s to peer...\n", filePath)

	for {
		n, err := tee.Read(buf)
		if n > 0 {
			totalBytes += n
			fmt.Printf("📤 [Sender]: Read & sent %d bytes | Total: %d bytes\n", n, totalBytes)
		}
		if err != nil {
			break
		}
		time.Sleep(30 * time.Millisecond)
	}

	fmt.Println("🏁 Finished streaming file!")
}

func (s *Session) RecieveAudio() {

	buf := make([]byte, 1500)
	totalBytes := 0

	for {
		n, err := s.conn.Read(buf)
		if err != nil {
			fmt.Println("Connection closed")
			return
		}
		if n == 0 {
			continue
		}

		totalBytes += n

		// Show preview of first 8 bytes in Hex (e.g. "ff fb 90 64...")
		previewLen := 8
		if n < previewLen {
			previewLen = n
		}
		fmt.Printf("📥 [Receiver]: Got %d bytes | Hex Preview: [% X...] | Total: %d bytes\n",
			n, buf[:previewLen], totalBytes)
	}
}
